### ISSUE TITLE
Image for Devuan?

### ISSUE THREAD

**Issue by markosc** [paolosabatino/armbian-build#2]
I do not know if it will be possible to add the "Devuan"(clone debian) image because it does not use "systemd" and uses "sysvinit" which works much better in the android box tv with little ram and cpu, thanks.

**Comment by paolosabatino** [comment]
Hello, I don't really know anything about the Devuan ecosystem and package handling and I'm afraid this is not the right place for a feature request, since this fork is mostly towards hardware support.

Maybe you can discuss about with other Armbian users and have more profit on General Chit Chat community forums: https://forum.armbian.com/forum/10-general-chit-chat/
